### PR TITLE
Updated Namecheap DDNS Service

### PR DESCRIPTION
**Pull request by Austin-Metke**
To provide better error messages for those using Namecheap, I'm parsing the XML response given by the Namecheap DDNS, while I was at it I implemented the ability to update multiple subdomains if more than 1 subdomain was provided. Java has no native way to parse XML, from my research I would've had to import some sort of library to do so. I figured importing an XML parsing library just for Namecheap would be unnecessary, as such I'm just taking in the server response as one big string, and checking if it contains anything pertaining to an error. This doesn't like a great solution, but it works as intended.

### CODE REVIEW

**Comment by Steve-Tech** [comment]
Wow, thanks, this is amazing.

Also sorry, I don't really have the time to maintain this much, did you want to be made a collaborator so you can merge whenever, create versions, and etc?

**Comment by Steve-Tech** [comment]
Hey @Austin-Metke, do you mind if I re-license this project as GPLv3? Currently there is no license, which I believe means we fully own the rights to our commits, and I'd like to make this a little more permissive before I do some more stuff with it.

**Comment by Austin-Metke** [comment]
> Hey @Austin-Metke, do you mind if I re-license this project as GPLv3? Currently there is no license, which I believe means we fully own the rights to our commits, and I'd like to make this a little more permissive before I do some more stuff with it.

Of course! Apologies for the late reply, FOSS for the win! If you'll still have me as a collaborator I'd much appreciate it as well.

**Comment by Steve-Tech** [comment]
> Of course! Apologies for the late reply, FOSS for the win!

Epic, thank you!

> If you'll still have me as a collaborator I'd much appreciate it as well.

You'll still be a contributor, but I probably won't make you a collaborator unless you start making a bunch of PRs again, as that comment was made almost 4 years ago. Sorry.

**Pull request merged**
